server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/studs
    username: login
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
token:
  signing:
    key: key
