server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/studs
    username: s367243
    password: 10s5iDYWGyVq2DuB
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855